// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-latest-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { z } from "npm:zod@^3.25.76";
var list_latest_articles_default = defineTool({
  name: "list_latest_articles",
  title: "List latest articles",
  description: "List the most recently published Amaica Media articles, optionally filtered by category or region.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many articles to return (max 50)."),
    category: z.enum(["music", "film", "tv", "events", "celebrity", "culture", "Our Legends"]).optional().describe("Filter by category."),
    region: z.enum(["western_kenya", "national"]).optional().describe("Filter by region.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category, region }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    let q = supabase.from("drafts").select("id, headline, lede, category, region, hero_image_url, published_at, byline").eq("status", "published").order("published_at", { ascending: false, nullsFirst: false }).limit(limit);
    if (category) q = q.eq("category", category);
    if (region) q = q.eq("region", region);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_article_default = defineTool2({
  name: "get_article",
  title: "Get article",
  description: "Fetch the full body and metadata of a published Amaica Media article by its id.",
  inputSchema: {
    id: z2.string().uuid().describe("The article id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    const { data, error } = await supabase.from("drafts").select("id, headline, lede, body, category, region, hero_image_url, published_at, byline, sources").eq("id", id).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Article not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/tools/list-legends.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_legends_default = defineTool3({
  name: "list_legends",
  title: "List legends",
  description: "List African entertainment legends in the Amaica 'Our Legends' roster.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25).describe("How many legends to return."),
    country: z3.string().optional().describe("Filter by country name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, country }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    let q = supabase.from("legends").select("id, name, country, era, field, short_bio, impact, image_url").eq("active", true).order("name").limit(limit);
    if (country) q = q.eq("country", country);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { legends: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "amaica-media-mcp",
  title: "Amaica Media MCP",
  version: "0.1.0",
  instructions: "Tools for Amaica Media, a Western Kenya-focused entertainment newsroom. Use `list_latest_articles` to browse recent published stories, `get_article` for the full body of a specific article, and `list_legends` to explore the 'Our Legends' roster.",
  tools: [list_latest_articles_default, get_article_default, list_legends_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
