// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-latest-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { z } from "npm:zod@^3.25.76";
function countWords(text) {
  if (!text) return 0;
  const stripped = String(text).replace(/<[^>]+>/g, " ");
  const matches = stripped.trim().match(/\S+/g);
  return matches ? matches.length : 0;
}
var list_latest_articles_default = defineTool({
  name: "list_latest_articles",
  title: "List latest articles",
  description: "List the most recently published Amaica Media articles, optionally filtered by category or region. Returns a strict typed array of {id, headline, lede, byline, category, region, status, hero_image_url, published_at, word_count, source_count, is_legend}.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many articles to return (max 50)."),
    category: z.enum(["music", "film", "tv", "events", "celebrity", "culture", "Our Legends"]).optional().describe("Filter by category."),
    region: z.enum(["western_kenya", "national"]).optional().describe("Filter by region.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category, region }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    let q = supabase.from("drafts").select("id, headline, lede, body, category, region, hero_image_url, published_at, byline, sources, status").eq("status", "published").order("published_at", { ascending: false, nullsFirst: false }).limit(limit);
    if (category) q = q.eq("category", category);
    if (region) q = q.eq("region", region);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const articles = (data ?? []).map((d) => ({
      id: d.id,
      headline: d.headline,
      lede: d.lede ?? "",
      byline: d.byline ?? null,
      category: d.category ?? null,
      region: d.region ?? null,
      status: d.status,
      hero_image_url: d.hero_image_url ?? null,
      published_at: d.published_at ?? null,
      word_count: countWords(d.body),
      source_count: Array.isArray(d.sources) ? d.sources.length : 0,
      is_legend: d.category === "Our Legends"
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(articles) }],
      structuredContent: { articles }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z2 } from "npm:zod@^3.25.76";
function countWords2(text) {
  if (!text) return 0;
  const stripped = String(text).replace(/<[^>]+>/g, " ");
  const matches = stripped.trim().match(/\S+/g);
  return matches ? matches.length : 0;
}
var get_article_default = defineTool2({
  name: "get_article",
  title: "Get article",
  description: "Fetch a published Amaica Media article by id. Returns a strict typed payload with headline, lede, body, byline, category, region, status, published_at, hero_image_url, word_count, sources (array of {url,title?,note?,section?}), and legend info when the article is an Our Legends feature.",
  inputSchema: {
    id: z2.string().uuid().describe("The article id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    const { data, error } = await supabase.from("drafts").select(
      "id, headline, lede, body, category, region, hero_image_url, published_at, byline, sources, status, template_type, updated_at"
    ).eq("id", id).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Article not found" }], isError: true };
    const rawSources = Array.isArray(data.sources) ? data.sources : [];
    const sources = rawSources.map((s) => {
      if (typeof s === "string") return { url: s };
      if (s && typeof s === "object") {
        return {
          url: typeof s.url === "string" ? s.url : "",
          title: typeof s.title === "string" ? s.title : void 0,
          note: typeof s.note === "string" ? s.note : void 0,
          section: typeof s.section === "string" ? s.section : void 0
        };
      }
      return { url: "" };
    }).filter((s) => s.url);
    let legend = null;
    if (data.category === "Our Legends") {
      const { data: lf } = await supabase.from("legend_features").select("legend_id, legends:legend_id ( id, name, country )").eq("draft_id", data.id).maybeSingle();
      const l = lf?.legends;
      if (l) legend = { id: l.id, name: l.name, country: l.country ?? null };
    }
    const article = {
      id: data.id,
      headline: data.headline,
      lede: data.lede ?? "",
      body: data.body ?? "",
      byline: data.byline ?? null,
      category: data.category ?? null,
      region: data.region ?? null,
      status: data.status,
      template_type: data.template_type ?? null,
      hero_image_url: data.hero_image_url ?? null,
      published_at: data.published_at ?? null,
      updated_at: data.updated_at ?? null,
      word_count: countWords2(data.body),
      sources,
      legend
    };
    return {
      content: [{ type: "text", text: JSON.stringify(article) }],
      structuredContent: { article }
    };
  }
});

// src/lib/mcp/tools/list-legends.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_legends_default = defineTool3({
  name: "list_legends",
  title: "List legends",
  description: "List African entertainment legends in the Amaica 'Our Legends' roster.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25).describe("How many legends to return."),
    country: z3.string().optional().describe("Filter by country name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, country }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    let q = supabase.from("legends").select("id, name, country, era, field, short_bio, impact, image_url").eq("active", true).order("name").limit(limit);
    if (country) q = q.eq("country", country);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { legends: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-articles.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z4 } from "npm:zod@^3.25.76";
function countWords3(text) {
  if (!text) return 0;
  const stripped = String(text).replace(/<[^>]+>/g, " ");
  const matches = stripped.trim().match(/\S+/g);
  return matches ? matches.length : 0;
}
var WESTERN_KENYA_TERMS = [
  "western kenya",
  "kakamega",
  "kisumu",
  "bungoma",
  "busia",
  "vihiga",
  "siaya",
  "homa bay",
  "migori",
  "kisii",
  "nyamira",
  "trans nzoia",
  "uasin gishu",
  "eldoret",
  "nandi",
  "bomet",
  "kericho",
  "luhya",
  "luo",
  "kalenjin",
  "kisii",
  "nyanza",
  "rift valley"
];
var search_articles_default = defineTool4({
  name: "search_articles",
  title: "Search articles",
  description: "Full-text search of published Amaica Media articles by keywords across headline, lede, and body. Supports region scoping ('western_kenya', 'kenya', 'national', or 'all') so callers can focus on Western Kenya or broader Kenyan entertainment coverage. Returns a strict typed array of {id, headline, lede, byline, category, region, status, hero_image_url, published_at, word_count, source_count, is_legend, match_score}.",
  inputSchema: {
    query: z4.string().trim().min(2).max(200).describe("Keywords to search for (matched across headline, lede, and body)."),
    region_scope: z4.enum(["western_kenya", "kenya", "national", "all"]).default("all").describe(
      "Scope results by region. 'western_kenya' restricts to region='western_kenya' OR body/headline mentioning a Western Kenya county/town. 'kenya' includes both national and western_kenya rows. 'national' restricts to region='national'. 'all' returns everything."
    ),
    category: z4.enum(["music", "film", "tv", "events", "celebrity", "culture", "Our Legends"]).optional().describe("Optional category filter."),
    limit: z4.number().int().min(1).max(50).default(20).describe("Maximum results to return (max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, region_scope, category, limit }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    const tokens = query.split(/\s+/).map((t) => t.replace(/[%_,()]/g, "").trim()).filter((t) => t.length >= 2).slice(0, 6);
    if (tokens.length === 0) {
      return { content: [{ type: "text", text: "Query too short" }], isError: true };
    }
    const orClauses = [];
    for (const t of tokens) {
      const esc = t.replace(/"/g, "");
      orClauses.push(`headline.ilike.%${esc}%`);
      orClauses.push(`lede.ilike.%${esc}%`);
      orClauses.push(`body.ilike.%${esc}%`);
    }
    let q = supabase.from("drafts").select("id, headline, lede, body, category, region, hero_image_url, published_at, byline, sources, status").eq("status", "published").or(orClauses.join(",")).order("published_at", { ascending: false, nullsFirst: false }).limit(Math.min(limit * 3, 150));
    if (category) q = q.eq("category", category);
    if (region_scope === "national") q = q.eq("region", "national");
    else if (region_scope === "kenya") q = q.in("region", ["national", "western_kenya"]);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const lowerTokens = tokens.map((t) => t.toLowerCase());
    const rows = (data ?? []).filter((d) => {
      if (region_scope !== "western_kenya") return true;
      if (d.region === "western_kenya") return true;
      const hay = `${d.headline ?? ""} ${d.lede ?? ""} ${d.body ?? ""}`.toLowerCase();
      return WESTERN_KENYA_TERMS.some((term) => hay.includes(term));
    });
    const scored = rows.map((d) => {
      const hay = `${d.headline ?? ""} ${d.lede ?? ""} ${d.body ?? ""}`.toLowerCase();
      let score = 0;
      for (const t of lowerTokens) {
        if ((d.headline ?? "").toLowerCase().includes(t)) score += 5;
        if ((d.lede ?? "").toLowerCase().includes(t)) score += 3;
        const bodyMatches = hay.split(t).length - 1;
        score += Math.min(bodyMatches, 5);
      }
      return {
        id: d.id,
        headline: d.headline,
        lede: d.lede ?? "",
        byline: d.byline ?? null,
        category: d.category ?? null,
        region: d.region ?? null,
        status: d.status,
        hero_image_url: d.hero_image_url ?? null,
        published_at: d.published_at ?? null,
        word_count: countWords3(d.body),
        source_count: Array.isArray(d.sources) ? d.sources.length : 0,
        is_legend: d.category === "Our Legends",
        match_score: score
      };
    }).sort((a, b) => b.match_score - a.match_score).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(scored) }],
      structuredContent: { query, region_scope, results: scored, count: scored.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "amaica-media-mcp",
  title: "Amaica Media MCP",
  version: "0.1.0",
  instructions: "Tools for Amaica Media, a Western Kenya-focused entertainment newsroom. Use `list_latest_articles` to browse recent published stories, `search_articles` to keyword-search with region scoping (western_kenya / kenya / national / all), `get_article` for the full body and typed metadata of a specific article, and `list_legends` to explore the 'Our Legends' roster.",
  tools: [list_latest_articles_default, search_articles_default, get_article_default, list_legends_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
